CREATE DATABASE AMACHAY
GO

USE AMACHAY
GO

CREATE TABLE PERSON
(
	Id INT NOT NULL IDENTITY,
	Name VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	Cel VARCHAR(20),
	Phone VARCHAR(20),
	Address VARCHAR(100),
	Dni VARCHAR(11),
	Mail VARCHAR(100),
	CONSTRAINT Pk_Person
	PRIMARY KEY(Id)
)
GO

CREATE TABLE CLIENT
(
	Id INT NOT NULL IDENTITY,
	IdPerson INT NOT NULL,
	Type VARCHAR(100),
	CONSTRAINT Pk_Client
	PRIMARY KEY(Id),
	CONSTRAINT Fk_Client_Person
	FOREIGN KEY(IdPerson) REFERENCES PERSON(Id)
)
GO

CREATE TABLE USERS
(
	Id INT NOT NULL IDENTITY,
	IdPerson INT NOT NULL,
	IdWarehouse INT NULL,
	UserName VARCHAR(20) NOT NULL,
	Password TEXT NOT NULL,
	Rol VARCHAR(100),
	CONSTRAINT Pk_User
	PRIMARY KEY(Id),
	CONSTRAINT Fk_User_Peson
	FOREIGN KEY(IdPerson) REFERENCES PERSON(Id),
    FOREIGN KEY(IdWarehouse) REFERENCES WAREHOUSE(Id)
)
GO

CREATE TABLE CATEGORY
(
	Id INT NOT NULL IDENTITY,
	Name VARCHAR(100) NOT NULL,
	CONSTRAINT Pk_Category
	PRIMARY KEY(Id)
)
GO

CREATE TABLE WAREHOUSE
(
	Id INT NOT NULL IDENTITY,
	Name VARCHAR(100) NOT NULL,
	Address VARCHAR(200) NOT NULL,
	State bit NOT NULL DEFAULT 1,
	CONSTRAINT Pk_WareHouse
	PRIMARY KEY(Id)
)
GO


CREATE TABLE PRODUCT
(
	Id INT NOT NULL IDENTITY,
	IdCategory INT NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(200) NOT NULL,
	Price NUMERIC(15,4) NOT NULL,
	Stock NUMERIC(15,4) NOT NULL,
	CONSTRAINT Pk_Product
	PRIMARY KEY(Id),
	CONSTRAINT Fk_Product_Category
	FOREIGN KEY(IdCategory) REFERENCES CATEGORY(Id)
)
GO

CREATE TABLE MOVEMENT
(
	Id INT NOT NULL IDENTITY,
	IdProduct INT NOT NULL,
	IdWareHouse INT NOT NULL,
	DateTime DATETIME NOT NULL,
	Quantity NUMERIC(15,2) NOT NULL,
	Type VARCHAR(100),
	IdUser INT NOT NULL,
	IdClient INT NOT NULL,
	LogDateTime DATETIME NULL,
	CONSTRAINT Pk_Movement
	PRIMARY KEY(Id),
	CONSTRAINT Fk_Movement_Product
	FOREIGN KEY(IdProduct) REFERENCES PRODUCT(Id),
	CONSTRAINT Fk_Movement_WareHouse
	FOREIGN KEY(IdWareHouse) REFERENCES WAREHOUSE(Id),
	CONSTRAINT Fk_Movement_User
	FOREIGN KEY(IdUser) REFERENCES USERS(Id),
	CONSTRAINT Fk_Movement_Client
	FOREIGN KEY(IdClient) REFERENCES CLIENT(Id)
)
GO

